Repository BlueFinBima/Helios, pull requests merged in 2020-02, with the labels that each got.

#183 New "Image Translucent", "Custom Tape" and "Custom Drum" controls
  Helios/Controls/CustomDrum.cs
  Helios/Controls/CustomDrumAppearanceEditor.xaml
  Helios/Controls/CustomDrumAppearanceEditor.xaml.cs
  Helios/Controls/CustomGaugeNeedle.cs
  Helios/Controls/CustomGaugeRenderer.cs
  Helios/Controls/CustomTape.cs
  Helios/Controls/CustomTapeAppearanceEditor.xaml
  Helios/Controls/CustomTapeAppearanceEditor.xaml.cs
  Helios/Controls/ImageTranslucent.cs
  Helios/Controls/ImageTranslucentAppearanceEditor.xaml
  Helios/Controls/ImageTranslucentAppearanceEditor.xaml.cs
  Helios/Controls/ImageTranslucentRenderer.cs
  Helios/Gauges/GaugeImage.cs
  Helios/Helios.csproj
Labels: enhancement

#195 restructured ResetMonitors
  Helios/HeliosSerializer.cs
  Helios/UndoManager.cs
  Profile Editor/MainWindow.xaml.cs
  Profile Editor/ViewModel/MonitorResetItem.cs
Labels: bug

#169 shared DCS interface editor
  Helios/ComponentModel/HeliosInterfaceAttribute.cs
  Helios/Helios.csproj
  Helios/Interfaces/DCS/Common/DCSInterfaceEditor.xaml
  Helios/Interfaces/DCS/Common/DCSInterfaceEditor.xaml.cs
  Helios/Interfaces/DCS/FA18C/FA18CInterface.cs
Labels: internal
